
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: dna_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - dna_network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: dna_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - dna_network

  db:
    image: mariadb:10.11
    container_name: dna_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dna_transportes
      MYSQL_USER: dna_user
      MYSQL_PASSWORD: dna_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dna_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dna_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: dna_user
      PMA_PASSWORD: dna_pass
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - dna_network

volumes:
  db_data:

networks:
  dna_network:
    driver: bridge
